jenkinsdata:
 build: jenkins-data
jenkinsmaster:
 image: my_jenkins
 volumes_from:
  - jenkinsdata
 ports:
  - "50000:50000"
jenkinsnginx:
 image: my_nginx
 ports:
  - "80:80"
 links:
  - jenkinsmaster:jenkinsmaster
